language: php

php:
  - 5.5


addons:
    code_climate:
        repo_token: 09e9d7a571b503fe6f37c7fc5ad6c32ac60f512efa1cc005863fc92db17f7fd1

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/

cache:
  directories:
  - $TRAVIS_BUILD_DIR/vendor
  - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update && composer --version

install:
  - travis_retry composer update --no-interaction --prefer-source

before_script:

script:
  - ./vendor/bin/phpunit -c phpunit.xml
  - ./vendor/bin/phpmd ./src text ruleset.xml

after_script:
  - ./vendor/bin/coveralls -c .coveralls.yml -v
  - CODECLIMATE_REPO_TOKEN=09e9d7a571b503fe6f37c7fc5ad6c32ac60f512efa1cc005863fc92db17f7fd1 ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
  - cat codeclimate.json

